"""The provider-neutral LLM vocabulary and adapter seam."""

from .content import (
    AssistantContentBlock,
    ContentBlock,
    ImageBlock,
    TextBlock,
    ThinkingBlock,
    ToolCallBlock,
    ToolResultContentBlock,
    UserContentBlock,
)
from .errors import AdapterProtocolError, LlmError, UnknownModelError
from .messages import (
    AssistantMessage,
    AssistantMessageDiagnostic,
    Cost,
    DeferredHandle,
    DiagnosticError,
    Message,
    StopReason,
    ToolResultMessage,
    Usage,
    UserMessage,
    text_of,
)
from .service import Adapter, LlmService, ModelId, Request
from .stream import (
    AssistantStream,
    StreamChunk,
    StreamDone,
    StreamError,
    StreamStart,
    TextDelta,
    TextEnd,
    TextStart,
    ThinkingDelta,
    ThinkingEnd,
    ThinkingStart,
    ToolCallDelta,
    ToolCallEnd,
    ToolCallStart,
    collect,
)
from .tools import (
    ConstrainedSampling,
    GrammarConstrainedSampling,
    JsonSchemaConstrainedSampling,
    ToolSchema,
)

__all__ = [
    "Adapter",
    "AdapterProtocolError",
    "AssistantContentBlock",
    "AssistantMessage",
    "AssistantMessageDiagnostic",
    "AssistantStream",
    "ConstrainedSampling",
    "ContentBlock",
    "Cost",
    "DeferredHandle",
    "DiagnosticError",
    "GrammarConstrainedSampling",
    "ImageBlock",
    "JsonSchemaConstrainedSampling",
    "LlmError",
    "LlmService",
    "Message",
    "ModelId",
    "Request",
    "StopReason",
    "StreamChunk",
    "StreamDone",
    "StreamError",
    "StreamStart",
    "TextBlock",
    "TextDelta",
    "TextEnd",
    "TextStart",
    "ThinkingBlock",
    "ThinkingDelta",
    "ThinkingEnd",
    "ThinkingStart",
    "ToolCallBlock",
    "ToolCallDelta",
    "ToolCallEnd",
    "ToolCallStart",
    "ToolResultContentBlock",
    "ToolResultMessage",
    "ToolSchema",
    "UnknownModelError",
    "Usage",
    "UserContentBlock",
    "UserMessage",
    "collect",
    "text_of",
]
