"""Differential corpora for the WP-14.1 ports (spec/harness.md WP-14.1 `HAR-010`/`HAR-011`).

- `data/ignore-corpus.json`: 6,000 pattern sets x 3 paths with pinned `ignore@7.0.5`'s `ignores()`
  result or thrown error (generated by minion-agent-docs
  assurance/layers/data/14-wp141/ignore-corpus.mjs under Node v22.15.1; win32 and Linux equal).
- `data/frontmatter-corpus.json`: 8,000 frontmatter texts with the reviewed reference subset
  reader's result (frontmatter-corpus.mjs; the reader is sound against yaml@2.9.0 per the
  characterization's section 8).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from minion_agent.skills._frontmatter import FrontmatterError, Number, Value, read_subset
from minion_agent.skills._ignore import Ignore, InvalidIgnorePattern

DATA = Path(__file__).parent / "data"


def test_ignore_port_matches_pinned_ignore_on_the_corpus() -> None:
    corpus = json.loads((DATA / "ignore-corpus.json").read_text(encoding="utf-8"))
    assert corpus["ignore"] == "7.0.5"
    mismatches = []
    checks = 0
    for case in corpus["cases"]:
        matcher = Ignore()
        matcher.add(case["patterns"])
        for result in case["results"]:
            checks += 1
            try:
                got: dict[str, Any] = {"ignored": matcher.ignores(result["path"])}
            except InvalidIgnorePattern:
                got = {"error": "SyntaxError"}
            want = {k: v for k, v in result.items() if k != "path"}
            if got != want:
                mismatches.append((case["patterns"], result["path"], want, got))
    assert checks == 18000
    assert not mismatches, mismatches[:5]


def _encode(value: Value) -> Any:
    if value is None or isinstance(value, (str, bool)):
        return value
    if isinstance(value, Number):
        return {"$number": value.text}
    if isinstance(value, list):
        return {"$seq": [_encode(v) for v in value]}
    return {"$map": [[k, _encode(v)] for k, v in value.items()]}


def test_frontmatter_reader_matches_the_reference_reader_on_the_corpus() -> None:
    cases = json.loads((DATA / "frontmatter-corpus.json").read_text(encoding="utf-8"))["cases"]
    assert len(cases) == 8000
    mismatches = []
    for case in cases:
        try:
            got: dict[str, Any] = {"ok": True, "value": _encode(read_subset(case["src"]))}
        except FrontmatterError:
            got = {"ok": False}
        want = {k: v for k, v in case.items() if k != "src"}
        if got != want:
            mismatches.append((case["src"], want, got))
    assert not mismatches, mismatches[:5]
